name = "AgentModel"
uuid = "388cb286-f2b1-4654-a3bb-2e137a39c658"
authors = ["Gabriel Torregrosa Cortés"]
version = "0.1.0"

[compat]
julia = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
